### ISSUE TITLE
The convert seems to be shut down

### ISSUE THREAD

**Issue by lomoya90** [documents4j/documents4j#102]
The error is reported for first time , after start my application . I traced the documents4j log and  found : the word_start.vbs script must be someting wrong : 
```java
' Start MS Word.
Set wordApplication = CreateObject("Word.Application")
If Err = 0 Then
  WScript.Quit -6 
End If
```

**Why return -6 after starting MS Word?**
```java
    /**
     * Represents an interaction with a converter where the converter did not respond.
     */
    CONVERTER_INACCESSIBLE(-6, Reaction.with(new Reaction.ConverterAccessExceptionBuilder("The converter seems to be shut down"))),

```

I changed the return value to 3 , then is OK.

**Comment by raphw** [comment]
This seems to be a bug indeed, what leaves the question why this was never discovered, it's been like this forever... Maybe the branch is overly rare...

**Comment by raphw** [comment]
Fixed on master.
