### ISSUE TITLE
Convert to docx results doc file on my machine.

### ISSUE THREAD

**Issue by fanthos** [documents4j/documents4j#122]
I am trying to convert document to `.docx`, but I got `.doc` file as result. After some search, I found that `com.documents4j.conversion.msoffice.MicrosoftWordFormat` using `wdFormatDocumentDefault` 16 as target type, it depends on computer's default settings.

To make sure every machine behaves same, the values `wdFormatXMLDocument` 12 or `wdFormatXMLDocumentMacroEnabled` 13 should be used to create `.docx` file.

**Comment by raphw** [comment]
Good catch, thanks. Merged!
