### ISSUE TITLE
support pptx in the remote API

### ISSUE THREAD

**Issue by plutext** [documents4j/documents4j#129]
com.documents4j.api.DocumentType needs updating to include DocumentType.MS_POWERPOINT

**Comment by raphw** [comment]
Would you file a PR?

**Comment by plutext** [comment]
I can confirm it works, using for example:

`java -jar documents4j-server-standalone-1.1.8-SNAPSHOT-shaded.jar http://192.168.0.33:9998 -Ecom.documents4j.conversion.msoffice.MicrosoftPowerpointBridge`
