### ISSUE TITLE
PowerPoint bridge activation

### ISSUE THREAD

**Issue by fredmafu** [documents4j/documents4j#130]
May I know how to do the "explicit activation"? Thank you.

**Comment by raphw** [comment]
On the command line? If you implement a custom converter, you can add it to the class path but the server will not activate it unless you include it on the command line by its class name.

**Comment by plutext** [comment]
Or in code, `enable(MicrosoftPowerpointBridge.class)` for example:  
```
LocalConverter.builder().enable(MicrosoftPowerpointBridge.class)
	               .baseFolder(tmpDir)
	               .workerPool(20, 25, 2, TimeUnit.SECONDS)
	               .processTimeout(30, TimeUnit.SECONDS)
	               .build();
```

**Comment by fredmafu** [comment]
Thanks @raphw and @plutext .

I had enabled the MicrosoftPowerpointBridge in code and still got the ExecutionException like "Could not complete conversion" or "The conversion finished unsuccessful with exitCode -6".

Finally I fix it by changing the Identity of the DCOM conf for "Microsoft PowerPoint Slide" from "This user" to "The interactive user" or "The launching user".
