### ISSUE TITLE
Too many "winword.exe" zombie processes

### ISSUE THREAD

**Issue by charles-wangkai** [documents4j/documents4j#138]
PR https://github.com/documents4j/documents4j/pull/137 seems wrong and needed to be rolled back.

The MS official documentation of [GetObject function](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/getobject-function) reads:

> Syntax
> GetObject([ pathname ], [ class ])

> If pathname is a zero-length string (""), GetObject returns a new object instance of the specified type. If the pathname argument is omitted, GetObject returns a currently active object of the specified type.

In three occurrences of GetObject function where this PR modifies, we all want to find an existing currently running MS Word instance. In fact, this PR causes `word_shutdown.vbs` not actually work because it would create a new instance and quit the new one then, however, we should quit the existing instance instead. As a result of failing cleanup, we may end up with many `winword.exe` zombie processes.

_Originally posted by @charles-wangkai in https://github.com/documents4j/documents4j/issues/137#issuecomment-1200452690_

**Comment by raphw** [comment]
Darn, good catch. Do you have an idea how to otherwise fix the proposed problem?

**Comment by charles-wangkai** [comment]
In my opinion, it is enough to [revert the pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/reverting-a-pull-request). What do you think?

**Comment by charles-wangkai** [comment]
@raphw Thanks for your quick fix (https://github.com/documents4j/documents4j/commit/7ab9c20924c221e68bd0e25fa836f0b318233f2d)! Could you please build a release or how can I get the snapshot artifacts from Maven?

**Comment by raphw** [comment]
I made a release just now.

**Comment by charles-wangkai** [comment]
That's great. Thanks!
