### ISSUE TITLE
Missing enable option on ServerStandalone help option

### ISSUE THREAD

**Issue by jromeroortega95** [documents4j/documents4j#151]
On the ServerStandalone the options `-ssl` and `--enable` share the short key `-E` so the enable option is not shown on the help page

![image](https://github.com/documents4j/documents4j/assets/14921344/d08307fe-8d74-40e1-a3ab-427c36db7b44)

I needed to use the enable option to activate the PowerPoint converter, but I had to look for the option in the code to find what is the enable key. They should have a different short key, maybe changing the ssl option to -C (for ssl Context) ?

**Comment by raphw** [comment]
That is an oversight.

Could you adjust it and send a PR?
