### ISSUE TITLE
Exporting excel to PDF in landscape format.

### ISSUE THREAD

**Issue by mrtinkz** [documents4j/documents4j#27]
Hi,

I am not really sure about the vb scripting but seems like excel spreadsheet with the landscape formatting are not being generated in the same way when converted into pdf. Not sure if this has something to do with the vb scripting https://msdn.microsoft.com/en-us/library/bb238907(v=office.12).aspx

I might be wrong, could you please guide me how to export the file in a landscape format. Thanks

**Comment by raphw** [comment]
Hi, thanks for the feedback. Do you receive an error when exporting in landscape format or did the result turn out differntly then expected? Can you check your Windows system log for what went wrong?

If this does not work, this would be a starting point to find the error.

**Comment by mrtinkz** [comment]
Hi thanks for the reply, 

I haven't seen any errors in the process. All i did was to export an excel file which is in landscape layout into the pdf format. But the pdf generated in the portrait format (Probably it is not considering the excel layout settings). In other sense if i manually export using the export option from the excel the pdf is being exported in the landscape format. So I was pointing to the excel_convert.vbs under the documents4j-transformer-msoffice-excel/src/main/resources. I was assuming any specific configuration about the file would fix this problem. The link i provided you was about (IncludeDocProperties	Optional	Variant	Set to True to indicate that document properties should be included or set to False to indicate that they are omitted.) thought if this setting has anything to do with it. Or you might try generating a pdf out of an excel which has landscape layout and see it the pdf file is generated in portrait. Hope i could explain the problem :-)

**Comment by mrtinkz** [comment]
check this line on 42, should the option IncludeDocProperties be configured to true ? so that i considers any excel document layout properties ? am still guessing not sure.

excelDocument.ExportAsFixedFormat xlTypePDF, outputFile

**Comment by raphw** [comment]
I do not currently have a lot of time, could you clone the project and test the change by editing the file? Everything should work out of the box, I am happy enough to test it some time this weekend and push a new version if it fixes the issue.

**Comment by mrtinkz** [comment]
Sure, I will try to make those changes. Thanks

**Comment by raphw** [comment]
Brilliant, ping me if you need any help or feedback on the way!

**Comment by mrtinkz** [comment]
Hi Could you please test and merge the changes. When you find time. Thanks

**Comment by raphw** [comment]
see my comment on your commit.

**Comment by raphw** [comment]
This does not seem to work. Thank you for the suggestion but I do not think the VBA API is rich enough.
