### ISSUE TITLE
Can't deploy demo 1.0.3-SNAPSHOT

### ISSUE THREAD

**Issue by SeriousSem** [documents4j/documents4j#28]
> $ mvn jetty:run
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building documents4j-local-demo 1.0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> jetty-maven-plugin:7.6.3.v20120416:run (default-cli) @ documents4j-lo                                                                   cal-demo >>>
[WARNING] The POM for com.documents4j:documents4j-local:jar:1.0.3-SNAPSHOT is mi                                                                   ssing, no dependency information available
[WARNING] The POM for com.documents4j:documents4j-transformer-msoffice-word:jar:                                                                   1.0.3-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.documents4j:documents4j-transformer-msoffice-excel:jar                                                                   :1.0.3-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.257s
[INFO] Finished at: Mon Feb 29 14:14:44 CET 2016
[INFO] Final Memory: 7M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project documents4j-local-demo: Could not reso                                                                   lve dependencies for project com.documents4j:documents4j-local-demo:war:1.0.3-SN                                                                   APSHOT: The following artifacts could not be resolved: com.documents4j:documents                                                                   4j-local:jar:1.0.3-SNAPSHOT, com.documents4j:documents4j-transformer-msoffice-wo                                                                   rd:jar:1.0.3-SNAPSHOT, com.documents4j:documents4j-transformer-msoffice-excel:ja                                                                   r:1.0.3-SNAPSHOT: Could not find artifact com.documents4j:documents4j-local:jar:                                                                   1.0.3-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit                                                                   ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea                                                                   d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso                                                                   lutionException

However after downgrading to the 1.0.2 it works perfectly.

**Comment by raphw** [comment]
It seems like there is a snapshot dependency that isnot fulfilles. Did you build the snapshot?

**Comment by SeriousSem** [comment]
Nvm, my fault. After building the snapshot it starts correctly.

**Comment by suri-pkl** [comment]
Hi , I am getting the below error,  i am new to this documents4j, May i know how to rectify below, I saw the answer above that need to build the snapshot to overcome the error, how can I build the snapshot. Thanks

[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< com.documents4j:documents4j-local-demo >---------------
[INFO] Building documents4j-local-demo 1.0.4-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO]
[INFO] >>> jetty-maven-plugin:7.6.3.v20120416:run (default-cli) > test-compile @ documents4j-local-demo >>>
[WARNING] The POM for com.documents4j:documents4j-local:jar:1.0.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.documents4j:documents4j-transformer-msoffice-word:jar:1.0.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.documents4j:documents4j-transformer-msoffice-excel:jar:1.0.4-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.156 s
[INFO] Finished at: 2018-07-24T14:57:04+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project documents4j-local-demo: Could not resolve dependencies for project com.documents4j:documents4j-local-demo:war:1.0.4-SNAPSHOT: The following artifacts could not be resolved: com.documents4j:documents4j-local:jar:1.0.4-SNAPSHOT, com.documents4j:documents4j-transformer-msoffice-word:jar:1.0.4-SNAPSHOT, com.documents4j:documents4j-transformer-msoffice-excel:jar:1.0.4-SNAPSHOT: Could not find artifact com.documents4j:documents4j-local:jar:1.0.4-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by raphw** [comment]
Are you building the complete project before running it?

**Comment by suri-pkl** [comment]
I ran mvn package command on command line, I got this
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< com.documents4j:documents4j-local-demo >---------------
[INFO] Building documents4j-local-demo 1.0.4-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[WARNING] The POM for com.documents4j:documents4j-local:jar:1.0.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.documents4j:documents4j-transformer-msoffice-word:jar:1.0.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.documents4j:documents4j-transformer-msoffice-excel:jar:1.0.4-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.008 s
[INFO] Finished at: 2018-07-25T15:44:48+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project documents4j-local-demo: Could not resolve dependencies for project com.documents4j:documents4j-local-demo:war:1.0.4-SNAPSHOT: The following artifacts could not be resolved: com.documents4j:documents4j-local:jar:1.0.4-SNAPSHOT, com.documents4j:documents4j-transformer-msoffice-word:jar:1.0.4-SNAPSHOT, com.documents4j:documents4j-transformer-msoffice-excel:jar:1.0.4-SNAPSHOT: Could not find artifact com.documents4j:documents4j-local:jar:1.0.4-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by raphw** [comment]
You have to build the root project to make the dependent modules available on your machine.

**Comment by raphw** [comment]
You need to run mvn install on root to publish the snapshots to your local maven repository.

**Comment by suri-pkl** [comment]
Thank you so much it worked,  and i am try to convert via browser via http://localhost:8080 and when i select the file  source file type as application/pdf and target file as application/msword, the converted version is storing <filename>.pdf.docx  and was all junk characters, am i choosing the correct file type?
 extract from the converted version (.docx)
%PDF-1.5
%µµµµ
1 0 obj
<</Type/Catalog/Pages 2 0 R/Lang(en-US) /StructTreeRoot 33 0 R/MarkInfo<</Marked true>>/Metadata 275 0 R/ViewerPreferences 276 0 R>>
endobj
2 0 obj
<</Type/Pages/Count 5/Kids[ 3 0 R 16 0 R 18 0 R 22 0 R 30 0 R] >>
endobj
3 0 obj
<</Type/Page/Parent 2 0 R/Resources<</Font<</F1 5 0 R/F2 9 0 R/F3 11 0 R/F4 13 0 R>>/ExtGState<</GS7 7 0 R/GS8 8 0 R>>/XObject<</Image15 15 0 R>>/ProcSet[/PDF/Text/ImageB/ImageC/ImageI] >>/MediaBox[ 0 0 609 791.04] /Contents 4 0 R/Group<</Type/Group/S/Transparency/CS/DeviceRGB>>/Tabs/S/StructParents 0>>
endobj
4 0 obj
<</Filter/FlateDecode/Length 3113>>
stream
xœ½[[SÛH ~§ŠÿÐÖ nÔ­ûÔÔÔ ¹

**Comment by raphw** [comment]
What happens if you convert the file with Word manually?

**Comment by suri-pkl** [comment]
manually i am able to convert.

**Comment by raphw** [comment]
Then it should be possible using the API. Did you try doing it programmatically first? It might be an error in the demo application or in the converter itself.

**Comment by suri-pkl** [comment]
ok Thanks, I will try to do it through program, yes could be some error in demo application.
