### ISSUE TITLE
Not able to redirect the log to a file with documents4j-server-standalone-1.0.2-shaded

### ISSUE THREAD

**Issue by torefredriksen** [documents4j/documents4j#32]
Hi.
We are currently using documents4j-server-standalone-0.2.1-shaded to convert our office douments to pdf.

I would like to upgrade to version 1.0.2.

However, it looks like there is a bug in the commandline parsing in version 1.0.2 which makes it impossible to redirect the logging to a file. 

The problem can be reproduced by running 1.0.2 from a windows command promt like this : 

C:\PDFKonv\old>"C:\Program Files\Java\jre1.8.0_91\bin\java.exe" -jar documents4j-server-standalone-1
.0.2-shaded.jar -F "C:\PDFKonv\temp" -L "C:\logs\log.txt" http://APP204800:8080 -V "info"

10:33:30.027 [main] ERROR c.d.standalone.StandaloneServer - The documents4j server terminated with a
n unexpected error
joptsimple.OptionArgumentConversionException: Cannot parse argument 'C:\logs\log.txt' of option [arg
uments]
.
.
Error: Cannot parse argument 'C:\logs\log.txt' of option [arguments]
## Use option -? to display a list of legal commands.

For comparison, this is how the command outputs on the version 0.2.1

C:\PDFKonv>"C:\Program Files\Java\jre1.8.0_91\bin\java.exe" -jar documents4j-server-standalone-0.2.1
-shaded.jar -F "C:\PDFKonv\temp" -L "C:\logs\log.txt" http://APP204800:8080 -V "info"
Logging: The log is written to C:\logs\log.txt
Logging: The log level is set to INFO
Welcome to the documents4j server!
on jul 13 10:39:09 CEST 2016: Started server on 'http://APP204800:8080'
The documents4j server is up and running. Hit the enter key to shut it down...

**Comment by raphw** [comment]
I am planning a new version of documents4j in the near future where I fix a few other bugs, as well. This one will be included in that version. Thanks for reporting.

**Comment by torefredriksen** [comment]
Thanks a lot for the reply. I have one further question. Does documents4j have bultin log rotate, or do we have to do that "manually" ?

**Comment by raphw** [comment]
documents4j uses logback. You can configure the logging as described in their manual: http://logback.qos.ch/manual/appenders.html

**Comment by torefredriksen** [comment]
Thanks :+1:

**Comment by raphw** [comment]
I did a copy paste mistake when adding the command line switch for SSL and remapped the logging constants to those for SSL. Therefore, nothing could be parsed anymore. I fixed this on master and will include it in the next release which is coming soon. Sorry for the long wait.

**Comment by torefredriksen** [comment]
Hi, thank you :-)

Tore
