### ISSUE TITLE
Request for permissions ((java.io.FilePermission "<<ALL FILES>>" "execute")) Security Risk ?

### ISSUE THREAD

**Issue by mistaguy** [documents4j/documents4j#35]
I have looked at the library again and it request for that permission. I believe its a security risk. Can it be dealt away with ?

**Comment by raphw** [comment]
documents4j does of course need to access files. It needs to execute scripts which is why this is required. documents4j does not expose any such routines so it is safe to give this permission.

**Comment by mistaguy** [comment]
When the policy file is in the context of document4j alone then its definitely okay but document4j is however being used in a document app for [Mendix](http://mendix.com) that requires a policy file to be defined for the entire application and hence adding the permission exposes the entire application to any other jar file to use the same permission. so if jar files are not  cautiously added then someone can take advantage. I will ask a similar question in the mendix groups and get response
