### ISSUE TITLE
conversion failed for unknown reason

### ISSUE THREAD

**Issue by binlebin** [documents4j/documents4j#38]
Hello Rafael,

Awesome and super useful library. I recently experienced a bug and was able to fix it. I hope you check if this is a real bug and  fix this bug in the next version to help other users.

- Version of documents4j: 1.0.3
- Code that triggers:
Utility.getConverter().convert(inFile).as(inputType).to(outFile).as(DocumentType.PDF).prioritizeWith(IConverter.JOB_PRIORITY_HIGH).execute();
- Exception message: conversion failed for unknown reason
- Platform: Windows 7, 64bit
- Reason: Installation into a folder that has a space, e.g., my application is installed into C:\My Prog
- Fix: Removed the space, e.g., my application is installed into C:\MyProg
Clearly, this fix will not work if you install into Program Files, e.g., C:\Program Files\MyProg

Regards,
Anh

**Comment by raphw** [comment]
I was sure I had fixed that but it seems like I missed something. I will need to retry this.

**Comment by raphw** [comment]
Hey, can you double-check that you are using the most recent version? I have tried all combinations of spaces in source and target files and in the converters run folder. All of them seem to work with 1.0.3. Maybe you are still using an old version?

**Comment by binlebin** [comment]
Hello Rafael,

Yes, I have used 1.0.3. I attached the jar files I used in my build in case they are useful to you.

Regards,
Anh











[Archive.zip](https://github.com/documents4j/documents4j/files/762745/Archive.zip)
