### ISSUE TITLE
try error!

### ISSUE THREAD

**Issue by AlexanLee** [documents4j/documents4j#40]
when i try ：mvn jetty:run
why i get's this error:
Failed to execute goal on project documents4j-local-demo: Could not resolve dependencies for project com.documents4j:documents4j-local-demo:war:1.0.4-SNAPSHOT: The following artifacts could not be resolved: com.documents4j:documents4j-local:jar:1.0.4-SNAPSHOT, com.documents4j:documents4j-transformer-msoffice-word:jar:1.0.4-SNAPSHOT, com.documents4j:documents4j-transformer-msoffice-excel:jar:1.0.4-SNAPSHOT: Could not find artifact com.documents4j:documents4j-local:jar:1.0.4-SNAPSHOT

**Comment by raphw** [comment]
Did you build the entire project prior to running the command?

**Comment by AlexanLee** [comment]
thanks , i have solved!
