### ISSUE TITLE
Extending documents4j to support document comparisons via Word

### ISSUE THREAD

**Issue by roded** [documents4j/documents4j#42]
Hi,
Thank you for this library, it is very well written and built.
I'm wondering whether it is possible to extend documents4j to be able to support calling the WINWORD process for the sake of comparing two Word documents.
Perhaps with a custom bridge or the like?
I'd much appreciate your thoughts.
Thanks

**Comment by raphw** [comment]
Thanks, glad you like it. I do not think that the comparison function is a good fit for being added to the library. It is already quite difficult to get running accross systems and the API does not relly invite for this form of call and I do not think this is a common requirement. 

You can however implement it yourself, I think if you mimic the behavior of documents4j, you can create your custom version that supports it.

**Comment by roded** [comment]
Thanks for the reply.
I might resort to comparing the documents4j resulting PDFs.
