### ISSUE TITLE
What causes a "converter seems to be shut down" error?

### ISSUE THREAD

**Issue by roded** [documents4j/documents4j#43]
Hi,
I'm running the standalone server on a machine with Windows Server 2008 R2 Standard and Microsoft Office 2010 32 bit.
It produces a "The converter seems to be shut down" error on a DOCX to PDFA conversion.
The server successfully starts a WINWORD.EXE and an EXCEL.EXE process at startup.
Any idea what the issue could be?
Thanks

Attached below is the entire server log.
 
>18:31:41.651 [main] INFO com.documents4j.ws.application.StandaloneWebConverterConfiguration - Standalone conversion server is starting: starting up local converter
>18:31:41.705 [main] DEBUG org.zeroturnaround.exec.ProcessExecutor - Executing [cmd, /S, /C, ""C:\Users\ADMINI\~1\AppData\Local\Temp\1494347501663-0\word_start986382467.vbs""] in C:\Users\ADMINI\~1\AppData\Local\Temp\1494347501663-0.
>18:31:41.710 [main] DEBUG org.zeroturnaround.exec.ProcessExecutor - Started java.lang.ProcessImpl@363a52f
>18:31:42.142 [WaitForProcess-java.lang.ProcessImpl@363a52f] DEBUG org.zeroturnaround.exec.WaitForProcess - java.lang.ProcessImpl@363a52f stopped with exit code 3
>18:31:42.150 [main] INFO com.documents4j.conversion.msoffice.MicrosoftWordBridge - From-Microsoft-Word-Converter was started successfully
>18:31:42.161 [main] DEBUG org.zeroturnaround.exec.ProcessExecutor - Executing [cmd, /S, /C, ""C:\Users\ADMINI\~1\AppData\Local\Temp\1494347501663-0\excel_start1903292155.vbs""] in C:\Users\ADMINI\~1\AppData\Local\Temp\1494347501663-0.
>18:31:42.162 [main] DEBUG org.zeroturnaround.exec.ProcessExecutor - Started java.lang.ProcessImpl@4c1f22f3
>18:31:42.444 [WaitForProcess-java.lang.ProcessImpl@4c1f22f3] DEBUG org.zeroturnaround.exec.WaitForProcess - java.lang.ProcessImpl@4c1f22f3 stopped with exit code 3
>18:31:42.447 [main] INFO com.documents4j.conversion.msoffice.MicrosoftExcelBridge - From-Microsoft-Excel-Converter was started successfully
>18:31:42.455 [main] INFO com.documents4j.job.LocalConverter - The documents4j local converter has started successfully
>18:31:42.455 [main] INFO com.documents4j.ws.application.StandaloneWebConverterConfiguration - Standalone conversion server is starting: local converter is started
>18:31:53.087 [Grizzly-worker(1)] INFO com.documents4j.ws.endpoint.AsynchronousConversionResponse - Registered conversion request for org.glassfish.jersey.server.ServerRuntime$AsyncResponder@124544
>18:31:53.233 [pool-2-thread-1] INFO com.documents4j.conversion.msoffice.MicrosoftWordBridge - Requested conversion from C:\Users\ADMINI\~1\AppData\Local\Temp\1494347501663-0776d8cdb->4094-4006-a77d-2c84805fc6d0\temp1 (application/vnd.openxmlformats-officedocument.wordprocessingml.document) to C:\Users\ADMINI\~1\AppData\Local\Temp\1494347501663-0\776d8cdb-4094-4006-a77d-2c84805fc6d0\temp2 (application/vnd.com.documents4j.pdf-a)
18:31:53.236 [pool-2-thread-1] DEBUG org.zeroturnaround.exec.ProcessExecutor - Executing [cmd, /S, /C, ""C:\Users\ADMINI\~1\AppData\Local\Temp\1494347501663-0\word_convert290731350.vbs" "C:\Users\ADMINI\~1\AppData\Local\Temp\1494347501663-0\776d8cdb-4094-4006-a77d-2c84805fc6d0\temp1" "C:\Users\ADMINI\~1\AppData\Local\Temp\1494347501663-0\776d8cdb-4094-4006-a77d-2c84805fc6d0\temp2" "999""] in C:\Users\ADMINI\~1\AppData\Local\Temp\1494347501663-0.
>18:31:53.238 [pool-2-thread-1] DEBUG org.zeroturnaround.exec.ProcessExecutor - Started java.lang.ProcessImpl@5f67048f
>18:31:53.328 [WaitForProcess-java.lang.ProcessImpl@5f67048f] DEBUG org.zeroturnaround.exec.WaitForProcess - java.lang.ProcessImpl@5f67048f stopped with exit code -6
>18:31:53.333 [pool-2-thread-1] INFO com.documents4j.ws.endpoint.AsynchronousConversionResponse - Sending exceptional response for org.glassfish.jersey.server.ServerRuntime$AsyncResponder@124544
>com.documents4j.throwables.ConverterAccessException: The converter seems to be shut down
>	at com.documents4j.util.Reaction$ConverterAccessExceptionBuilder.make(Reaction.java:117)
>	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
>	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70)
>	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48)
>	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36)
>	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11)
>	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
>	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>	at java.lang.Thread.run(Unknown Source)

**Comment by raphw** [comment]
Did you start Word manually and see if some form of Wizard is running? There is a script in the MS Word Bridge that you can run manually. If this message is shown, it indicates that the .NET script did not successfully get an instance of MS Word. To debug, you can take the script and run it manually, trying to tweak it. This VBS script is really just a few lines long.

**Comment by roded** [comment]
Thanks for your reply.
Word 2010 loads fine when started manually.
I ran `word_start.vbs` manually and it seems to be starting a new instance of Word for every execution - even if an existing WINWORD.exe is up (for the same user). So there's an issue with the script's connecting to an existing Word instance.
I suspect this is related to various changes we did on the environment (DCOM) to support a previous conversion implementation..

**Comment by raphw** [comment]
This means that the started instance is not accessible for the second run as the script checks if an instance is already running. This also explains why the conversion fails as the instance from the first run is not accessible to the second.

**Comment by roded** [comment]
By changing the Word DCOM application identity to "Launching User" the problem has been resolved.

**Comment by westeast** [comment]
> identity

How to change  the Word DCOM application identity to "Launching User"
