### ISSUE TITLE
com.documents4j.throwables.ConversionInputException

### ISSUE THREAD

**Issue by Soliax** [documents4j/documents4j#44]
Hi Raphw,

I'm encountering an error linked to the converter used when trying to convert file from XLS to MHTML.
For other type of conversion, I don't have any issue using your library.

Here the example document used for conversion :

CONVERTING : 

C:\Users\eantlal\workspace\ExcelConverter\Temp\081N1_3.32081N1_1.42081N1_1-FP-22052017.xls

TO 

C:\Users\eantlal\workspace\ExcelConverter\HTML\081N1_3.32081N1_1.42081N1_1-FP-22052017\081N1_3.32081N1_1.42081N1_1-FP-22052017.mhtml

Exception raised :

> ``Exception in thread "Thread-1" com.documents4j.throwables.ConversionInputException: No converter for conversion of application/vnd.ms-excel to application/x-mimearchive available

Stack trace :

	at com.documents4j.conversion.ConverterRegistry.lookup(ConverterRegistry.java:65)	at com.documents4j.conversion.DefaultConversionManager.startConversion(DefaultConversionManager.java:30)
	at com.documents4j.job.LocalFutureWrappingPriorityFuture.startConversion(LocalFutureWrappingPriorityFuture.java:50)
	at com.documents4j.job.LocalFutureWrappingPriorityFuture.startConversion(LocalFutureWrappingPriorityFuture.java:11)

	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:70)	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Log from your library :

```
mai 30, 2017 10:58:04 AM org.zeroturnaround.exec.stream.slf4j.Slf4jInfoOutputStream processLine
INFO: Microsoft (R) Windows Script Host Version 5.8
mai 30, 2017 10:58:04 AM org.zeroturnaround.exec.stream.slf4j.Slf4jInfoOutputStream processLine
INFO: Copyright (C) Microsoft Corporation. All rights reserved.
mai 30, 2017 10:58:04 AM org.zeroturnaround.exec.stream.slf4j.Slf4jInfoOutputStream processLine
INFO: 
mai 30, 2017 10:58:04 AM com.documents4j.conversion.msoffice.MicrosoftWordBridge startUp
INFO: From-Microsoft-Word-Converter was started successfully
mai 30, 2017 10:58:04 AM org.zeroturnaround.exec.stream.slf4j.Slf4jInfoOutputStream processLine
INFO: Microsoft (R) Windows Script Host Version 5.8
mai 30, 2017 10:58:04 AM org.zeroturnaround.exec.stream.slf4j.Slf4jInfoOutputStream processLine
INFO: Copyright (C) Microsoft Corporation. All rights reserved.
mai 30, 2017 10:58:04 AM org.zeroturnaround.exec.stream.slf4j.Slf4jInfoOutputStream processLine
INFO: 
mai 30, 2017 10:58:04 AM com.documents4j.conversion.msoffice.MicrosoftExcelBridge startUp
INFO: From-Microsoft-Excel-Converter was started successfully
mai 30, 2017 10:58:04 AM com.documents4j.job.LocalConverter <init>
INFO: The documents4j local converter has started successfully
```

Code used :

```
File excelFile = new File(inputFile.getAbsolutePath()), htmlFile = new File(outputFile.getAbsolutePath());
        	
htmlFile.getParentFile().mkdirs();

        	IConverter converterTest =  LocalConverter.builder()
                    .baseFolder(new File("C:\\Data Sync\\converter"))
                    .workerPool(20, 25, 2, TimeUnit.SECONDS)
                    .processTimeout(5, TimeUnit.SECONDS)
                    .build();

        	Boolean conversion = converterTest
        	                                .convert(excelFile).as(DocumentType.XLS)
        	                                .to(htmlFile).as(DocumentType.MHTML)
        	                                .prioritizeWith(1000) // optional
        	                                .execute();
```

I have OpenOffice/LibreOffice and Microsoft Office installed, and none of them could be use to convert xls to mhtml ? What software should I use to convert document ?

Best regards,

Anton L.

**Comment by raphw** [comment]
Can you convert an excel file to another format? I do not think that I have currently an html converter implemented. You can try to add that to the MS Excel bridge and send a PR.

**Comment by Soliax** [comment]
Hi,


Indeed I can convert an excel file to xml, PDF, etc.

I though that your library made the link between any java application, and a third parties software.
This third parties software (MicrosoftExcelBridge in my case) would than make the conversion.
Meaning, that any export/save format from the third parties software would be available for conversion.
I suppose you had to add a layer between them, and it's why the MHTML format is not supported by the microsoft bridge ?

Anyhow, thank for your support.


Best regards,


Anton L.

**Comment by raphw** [comment]
There is probably an easy fix to this. Have a look at https://github.com/documents4j/documents4j/blob/master/documents4j-transformer-msoffice/documents4j-transformer-msoffice-excel/src/main/java/com/documents4j/conversion/msoffice/MicrosoftExcelBridge.java, you might just need to add the annotation value for mhtml. Additionally, you would need to add the format here: https://github.com/documents4j/documents4j/blob/master/documents4j-transformer-msoffice/documents4j-transformer-msoffice-excel/src/main/java/com/documents4j/conversion/msoffice/MicrosoftExcelFormat.java

If you can make it work, send me a PR and I will merge it.
