### ISSUE TITLE
how to run documents4j server

### ISSUE THREAD

**Issue by xuzhu007** [documents4j/documents4j#86]
Hello, I have downloaded the source code of this project and it has been packaged and generated。But with  "java -jar documents4j-server-standalone-shaded.jar http://localhost:9998",i can't run.
can you help me, thanks a lot.

![image](https://user-images.githubusercontent.com/20570417/77533778-71d20c00-6ed2-11ea-9eb9-699f3a5aae60.png)

**Comment by raphw** [comment]
You're not supposed to use the sources jar but the executable binary.

**Comment by xuzhu007** [comment]
how can i get  the executable binary?  Sorry, I've been working on it all day

**Comment by raphw** [comment]
For example from Maven Central: https://search.maven.org/artifact/com.documents4j/documents4j-server-standalone/1.1.1/jar

**Comment by xuzhu007** [comment]
Hello, I found a syntax error in the documentation sample code,You need to remove the semicolon
![image](https://user-images.githubusercontent.com/20570417/77736702-9f8c9180-7047-11ea-9194-b43fc3a33942.png)
