### ISSUE TITLE
documents4j in docker container

### ISSUE THREAD

**Issue by dupinder** [documents4j/documents4j#97]
Hello @raphw ,
Thanks for this repo.
Is it possible to run documents4j in docker Linux container? If it's not possible then what are the alternates for Linux docker container?

**Comment by raphw** [comment]
The client, of course but the server requires MS Word which requires MS Windows.

**Comment by dupinder** [comment]
So what you think, is it a good practice to run a service on windows server and that windows server have MS Word ?

**Comment by raphw** [comment]
Yes, this is the way to go.

Also check the instructions on documents4j.com to see how to set it up with a service user.

**Comment by dupinder** [comment]
closing this question
